#!/bin/sh
################################################################################
#      This file is part of OpenELEC - http://www.openelec.tv
#      Copyright (C) 2009-2012 Stephan Raue (stephan@openelec.tv)
#
#  This Program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2, or (at your option)
#  any later version.
#
#  This Program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with OpenELEC.tv; see the file COPYING.  If not, write to
#  the Free Software Foundation, 51 Franklin Street, Suite 500, Boston, MA 02110, USA.
#  http://www.gnu.org/copyleft/gpl.html
################################################################################

if [ -z "$1" ]; then
  echo "usage $0 <tagname>"
  exit 0
fi

echo "getting sources..."
  if [ ! -d btrfs-progs.git ]; then
    git clone --branch v$1 --depth 1 git://git.kernel.org/pub/scm/linux/kernel/git/kdave/btrfs-progs.git btrfs-progs.git
  fi

echo "copying sources..."
  cp -R btrfs-progs.git btrfs-progs-$1

echo "cleaning sources..."
  rm -rf btrfs-progs-$1/.git

echo "packing sources..."
  tar cvJf btrfs-progs-$1.tar.xz btrfs-progs-$1

echo "remove temporary sourcedir..."
  rm -rf btrfs-progs-$1
